/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author SAMSUNG
 */
public class PedidoFeito extends javax.swing.JFrame {

    /**
     * Creates new form pedidofeito
     */
    public PedidoFeito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoPedidoFeito = new javax.swing.JLabel();
        textoNumPedido = new javax.swing.JLabel();
        numPedido = new javax.swing.JLabel();
        shop = new javax.swing.JLabel();
        slider = new javax.swing.JLabel();
        more = new javax.swing.JLabel();
        cart = new javax.swing.JLabel();
        config = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(130, 140, 143));

        textoPedidoFeito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoPedidoFeito.setForeground(new java.awt.Color(65, 71, 82));
        textoPedidoFeito.setText("Pedido feito");

        textoNumPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoNumPedido.setForeground(new java.awt.Color(65, 71, 82));
        textoNumPedido.setText("O número de seu pedido é");

        numPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numPedido.setForeground(new java.awt.Color(23, 252, 99));
        numPedido.setText("#5678");

        shop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop.png"))); // NOI18N

        slider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/level.png"))); // NOI18N

        more.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shcart.png"))); // NOI18N

        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(textoPedidoFeito))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(shop)
                        .addGap(41, 41, 41)
                        .addComponent(slider)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numPedido)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 153, Short.MAX_VALUE)
                                .addComponent(config)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(more)
                        .addGap(43, 43, 43)
                        .addComponent(cart))
                    .addComponent(textoNumPedido))
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(config)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoPedidoFeito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNumPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numPedido)
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop)
                            .addComponent(slider, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(more, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cart, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoFeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoFeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoFeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoFeito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoFeito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cart;
    private javax.swing.JLabel config;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel more;
    private javax.swing.JLabel numPedido;
    private javax.swing.JLabel shop;
    private javax.swing.JLabel slider;
    private javax.swing.JLabel textoNumPedido;
    private javax.swing.JLabel textoPedidoFeito;
    // End of variables declaration//GEN-END:variables
}
